### ISSUE TITLE
[Suggestion] - To Convert Database to MySQL

### ISSUE THREAD

**Issue by sadaftahir** [Iqra-Bakhtiyaar/Mango#1]
Hi, 

I have gone through your project, and the website seems very phenomenal. I like the layout and use of features. I would like to suggest an idea for improving the project. I believe that not many people use MongoDB and I have good use of SQL. Therefore I would love to change the format of the Database from MongoDB to SQL. Additionally, you have not provided proper documentation on how to set up the website so I might be willing to help you with that as well if possible.

**Comment by Iqra-Bakhtiyaar** [comment]
Hello sadaftahir

I appreciate the feedback you've provided. I'd be more than happy for you to change the format. If you require any further assistance on this then please let me know. Look forward to hearing from you soon. 

Regards Iqra
